spring.application.name=k-board-api

spring.datasource.url=jdbc:postgresql://localhost:5432/kboard
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

api.security.token.secret=${JWT_SECRET_K_BOARD_API}
api.aws.access-key=${AWS_ACCESS_KEY_ID}
api.aws.secret-key=${AWS_SECRET_ACCESS_KEY}
api.aws.bucket-url=https://k-board-images.s3.us-east-2.amazonaws.com/